version: 2
updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    # Maintain dependencies for npm
    - package-ecosystem: "npm"
      target-branch: "master"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: "increase"
      open-pull-requests-limit: 20
      commit-message:
          prefix: "fix"
          prefix-development: "build"
          include: "scope"
      groups:
          majorProd:
                applies-to: version-updates
                dependency-type: production
                update-types:
                    - "major"
                exclude-patterns:
                    - "rapiq"
          majorDev:
              applies-to: version-updates
              dependency-type: development
              exclude-patterns:
                  - "eslint"
                  - "nanoid"
                  - "chalk"
                  - "@faker-js/faker"
              update-types:
                  - "major"
          minorAndPatch:
                applies-to: version-updates
                update-types:
                    - "patch"
                    - "minor"
                exclude-patterns:
                    - "eslint-plugin-vue"
